<?php

namespace AppBundle\Repository;

/**
 * BuyingNotLogginUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyingNotLogginUserRepository extends \Doctrine\ORM\EntityRepository
{
}
