<?php

namespace AppBundle\Repository;

/**
 * FileToRentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileToRentalRepository extends \Doctrine\ORM\EntityRepository
{
}
