<?php

namespace AppBundle\Repository;

/**
 * MiniatureImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiniatureImageRepository extends \Doctrine\ORM\EntityRepository
{
}
