<?php

namespace AppBundle\Repository;

/**
 * OtherDeliveryDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherDeliveryDataRepository extends \Doctrine\ORM\EntityRepository
{
}
